### ISSUE TITLE
Lags. Fix it

### ISSUE THREAD

**Issue by yourconst** [kamyy/webgl-ray-tracer#4]
My laptop and phone freezes when I browse your demo.
Because startup rendering resolution / bouncing depth is too big.
Please fix it.
Eg. by asking these parameters before rendering or depends it on frame time

**Comment by kamyy** [comment]
Sorry for the really, really late reply! I did finally get some time this month to dig deeper into the issue. Some of the things I tried included moving the render loop into a web worker and making use of OffscreenCanvas in the web worker to update the DOM canvas. I thought this would have reduced the load on the main thread but to my surprise this wasn't the problem. It appears  the fragment shader running on the GPU is so expensive it's impacting the entire OS not just the browser thereby causing the whole machine to lag. To combat this I've paused the render loop when you hold down a mouse button when over the browser window. This helps when dragging sliders or when moving the camera around. I've also reduced the default # of samples to 10, which should lessen the time to finish a render.
